#include <iostream>
#include <Windows.h>
#include <conio.h>
#include <string>
#include <chrono>
#include <thread>
#include <boost/algorithm/string.hpp>
#include <time.h>
#include <fstream>
#include <curlpp/cURLpp.hpp>
#include <curlpp/Easy.hpp>
#include <curlpp/Options.hpp>
#include <filesystem>
